Repository Rishit-dagli/Python3-by-practice, pull requests merged in 2020-10, with the labels that each got.

#15 Add TF Hub blog by Rishit Dagli
  Blogs/building-better-ai-apps-with-tf-hub.md
Labels: Blogs, size/L

#14 Added Regression using sklearn example
  Machine Learning/sklearn examples/Linear Regression/Ecommerce Customers
  Machine Learning/sklearn examples/Linear Regression/Linear Regression .ipynb
  Machine Learning/sklearn examples/Linear Regression/readme.md
Labels: examples

#23 A Whirlwind Tour of Python
  EBooks/a-whirlwind-tour-of-python.epub
Labels: EBooks

#35 Create Issue templatea
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/M

#37 Added a new ebook
  Machine Learning/Machine-Learning-For-Dummies_IBM.pdf
Labels: EBooks

#43 Added Python Packaging User Guide
  EBooks/packaging-python-org-en-latest.pdf
Labels: EBooks

#48 adding new ML algorithm file -> KMeans Clustering
  Machine Learning/sklearn examples/K Mean Clustering/K-Mean Clustering .ipynb
  Machine Learning/sklearn examples/K Mean Clustering/K-means_convergence.gif
  Machine Learning/sklearn examples/K Mean Clustering/README.md
  Machine Learning/sklearn examples/K Mean Clustering/elbow method.png
Labels: examples

#49 Added Project Euler
  Project Euler/README.md
  Project Euler/problem_01/README.md
  Project Euler/problem_01/sol1.py
  Project Euler/problem_01/sol2.py
  Project Euler/problem_01/sol3.py
  Project Euler/problem_01/sol4.py
  Project Euler/problem_02/README.md
  Project Euler/problem_02/sol1.py
  Project Euler/problem_02/sol2.py
  Project Euler/problem_02/sol3.py
  Project Euler/problem_02/sol4.py
  Project Euler/problem_03/README.md
  Project Euler/problem_03/sol1.py
  Project Euler/problem_03/sol2.py
  Project Euler/problem_03/sol3.py
  Project Euler/problem_04/README.md
  Project Euler/problem_04/sol1.py
  Project Euler/problem_04/sol2.py
  Project Euler/problem_05/README.md
  Project Euler/problem_05/sol1.py
  Project Euler/problem_05/sol2.py
Labels: misc, size/XL

#63 Add K Means Blog
  Blogs/build-k-means-from-scratch.md
Labels: Blogs, size/L

#64 Add original blog links to posts contributed by Rishit-dagli
  Blogs/building-better-ai-apps-with-tf-hub.md
  Blogs/deploying-models-to-production-with-tf-model-server.md.md
Labels: Blogs, size/XS

#61 Machine Learning Algorithms image
  Machine Learning/Machine_Learning_Algorithms.pdf
Labels: misc

#67 Added Fibonacci Series in Introduction
  Training Modules/01 Introduction/1.08 Fibonacci Series/README.md
  Training Modules/01 Introduction/1.08 Fibonacci Series/fibonacci.py
Labels: size/M

#72 Logical Operator
  Training Modules/01 Introduction/1.09 Logical Operators/README.md
  Training Modules/01 Introduction/1.09 Logical Operators/solution.py
Labels: examples, size/M

#86 Project Euler Problem 06
  Project Euler/problem_06/README.md
  Project Euler/problem_06/problem6.py
Labels: size/M, stat:awaiting response

#90 add solution for Euler07
  Project Euler/problem_07/README.md
  Project Euler/problem_07/solution.py
Labels: size/M

#106 Added Ebook-Python Programming An Introduction...
  EBooks/python-programming-an-introduction-to-computer-science-2nd-edition.pdf
Labels: EBooks

#104 Training Module: Dynamic Programming
  Training Modules/04 Dynamic Programming/4.01 Minimum Coin Change/README.md
  Training Modules/04 Dynamic Programming/4.01 Minimum Coin Change/minCoinChange.py
Labels: awaiting review, size/M

#93 Dicts training module and store products problem
  Training Modules/02 Basic Data Types/2.06 Dicts/README.md
  Training Modules/02 Basic Data Types/2.06 Dicts/solution.py
Labels: examples, size/M

#113 Add Python Codecademy Ebook
  EBooks/Python Codecademy Pro Ebook.pdf
Labels: EBooks

#109 Training Module - Searching
  Training Modules/01 Introduction/1.08 Searching/Binary Search/Binary Search.py
  Training Modules/01 Introduction/1.08 Searching/Binary Search/README.md
  Training Modules/01 Introduction/1.08 Searching/Linear Search/Linear Search.py
  Training Modules/01 Introduction/1.08 Searching/Linear Search/README.md
Labels: examples, size/L

#88 Intro Numpy Examples
  Training Modules/Introduction to Numpy/Introduction to Numpy.ipynb
  Training Modules/Introduction to Numpy/README.md
Labels: examples, size/XXL

#60 Added Decision Tree and Random Forest to sklearn examples
  Machine Learning/sklearn examples/Decision Trees and Random Forests/DecisionTrees_and_RandomForests.ipynb
  Machine Learning/sklearn examples/Decision Trees and Random Forests/README.md
  Machine Learning/sklearn examples/Decision Trees and Random Forests/kyphosis.csv
Labels: examples, stat:awaiting response
